name: Mobile — Submit to Stores
on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'EAS profile to submit (production/preview)'
        required: true
        default: 'production'

jobs:
  submit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '18' }
      - name: Install EAS
        run: npm i -g eas-cli
      - name: Submit Android
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: |
          cd mobile-expo
          eas submit -p android --profile ${{ github.event.inputs.profile }} --non-interactive --android-track internal
      - name: Submit iOS
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
        run: |
          cd mobile-expo
          eas submit -p ios --profile ${{ github.event.inputs.profile }} --non-interactive
